name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Lint
        run: |
          npm run lint

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: node_modules/.bin/mocha -r ts-node/register --exit 'test/**.spec.ts'
